export type { Projection, ProjectionOpts } from './projection.ts'
export { createProjection } from './projection.ts'
export type { EventStore, ReadOpts } from './store.ts'
export { createStore, fileSnapshotBackend, jsonlBackend, memoryBackend, memorySnapshotBackend } from './store.ts'
export type { NewEvent, Reducer, Snapshot, SnapshotBackend, StoreBackend, StoredEvent } from './types.ts'
